### ISSUE TITLE
Второй вебхук по одной камере не срабатывает,  только перезапуск котейнера.

### ISSUE THREAD

**Issue by exotsk** [samoswall/Synology-Surveillance-Station-video-to-Telegram-with-prerecording#3]
2024-04-08 10:37:48,481 - [10][INFO] -  main - (main.py).webhookcam(230) - Receiv
ed IDCam: 18, 08.04.2024, 10:37:48                                               
2024-04-08 10:37:53,533 - [10][ERROR] -  main - (app.py).log_exception(825) - Exc
eption on /webhookcam [POST]                                                     
Traceback (most recent call last):                                               
  File "/opt/venv/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_
app                                                                              
    response = self.full_dispatch_request()                                      
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                      
  File "/opt/venv/lib/python3.12/site-packages/flask/app.py", line 869, in full_d
ispatch_request                                                                  
    rv = self.handle_user_exception(e)                                           
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                           
  File "/opt/venv/lib/python3.12/site-packages/flask/app.py", line 867, in full_d
ispatch_request                                                                  
    rv = self.dispatch_request()                                                 
         ^^^^^^^^^^^^^^^^^^^^^^^                                                 
  File "/opt/venv/lib/python3.12/site-packages/flask/app.py", line 852, in dispat
ch_request                                                                       
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)     
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     
  File "/app/main.py", line 240, in webhookcam                                   
    cursor.execute('UPDATE CamVideo SET video_offset = video_offset + 10000 WHERE
 cam_id = ?', (cam_id))                                                          
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current stat
ement uses 1, and there are 2 supplied.

**Comment by exotsk** [comment]
![CleanShot 2024-04-08 at 17 44 59@2x](https://github.com/samoswall/Synology-Surveillance-Station-video-to-Telegram-with-prerecording/assets/54969124/c3105643-73fc-48bd-b8f8-92dcc9665a80)

**Comment by exotsk** [comment]
https://qna.habr.com/q/754137 может быть это ?

**Comment by exotsk** [comment]
File "/app/main.py", line 240, in webhookcam
cursor.execute('UPDATE CamVideo SET video_offset = video_offset + 10000 WHERE
cam_id = ?', (cam_id,)) <-- запятую надо, так работает без ошибок. Но меняется только оффсет на 10000 от первого времени, что тоже неверно. видео приходит старое.

**Comment by samoswall** [comment]
Да, эта ошибка связана с выходом версии python 3.12
Сегодня вечером исправлю для новой версии

**Comment by exotsk** [comment]
спасибо

**Comment by exotsk** [comment]
здесь будет обновление ? и на другом форке ?

**Comment by samoswall** [comment]
Обновлен контейнер. 
Нужно удалить старый и установить заново.

**Comment by exotsk** [comment]
обновил, запускается вебхук, но видео приходят с оффестом +10 сек от записи в базе похоже.
![CleanShot 2024-04-10 at 18 01 56](https://github.com/samoswall/Synology-Surveillance-Station-video-to-Telegram-with-prerecording/assets/54969124/c6fc136c-342f-4fd1-bf25-f5b630f57e2b)
хотя времени уже 18:03

**Comment by exotsk** [comment]
запустил еще несколько раз подряд, все видео в этом же диапазоне приходят в районе 17:47 времени 18:07

**Comment by samoswall** [comment]
Убедитесь, что у Вас запись производится по детектору движения, с временем предзаписи 5 сек. Не 24/7 запись, а именно по детектору движения!
В папке камеры создаются маленькие файлы, в имени будет время обнаружения движения, длительность видео = 5 сек + движение + 5 сек

**Comment by exotsk** [comment]
ну конечно у меня 24.7. Не увидел ничего в мануале за этот нюанс/ Переключу, проверю
