### ISSUE TITLE
"idcam" для других камер

### ISSUE THREAD

**Issue by wzooroo** [samoswall/Synology-Surveillance-Station-video-to-Telegram-with-prerecording#4]
Привет! Как узнать при добавлении новой камеры номер "idcam"?
С одной камеры {"idcam":"1"} работало нормально, но как только добавил еще одну камеру непонятно как узнать ID. Хотя в Правилах Действия и в Событии САМ2 видна и можно выбрать хоть все камеры. И вообще другие "idcam" для других камер нужно прописывать или хватает только выбор в Событии остальных камер?

**Comment by samoswall** [comment]
Обычно idcam идет по порядку, лучший вариант удалить файл конфигурации, и при запуске бедет создан новый, в вашем случае с двумя камерами.
Правило действия для второй и последующих камер прописывать надо обязательно.

**Comment by wzooroo** [comment]
Спасибо!
То есть надо создавать для каждой камера свое правило действий? Или можно {"idcam":"1"} для каждой камеры через запятую прописать в Действие-Основной текст?

**Comment by samoswall** [comment]
Да. Для каждой камеры надо создавать свое правило действий.
Для первой камеры - {"idcam":"1"}
Для второй - {"idcam":"2"}
По этому сообщению, скрипт понимает в какой камере обнаружено движение и соответственно от какой камеры скачивать видео.
